// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/registry.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WorkerState is the lifecycle state of a worker as seen by the control plane.
type WorkerState int32

const (
	WorkerState_STARTING WorkerState = 0 // container up, model loading — router does not route here
	WorkerState_READY    WorkerState = 1 // model loaded, queue empty
	WorkerState_BUSY     WorkerState = 2 // processing requests, queue depth > 0
	WorkerState_DRAINING WorkerState = 3 // scaler scaling down — no new requests, waiting for in-flight
	WorkerState_DEAD     WorkerState = 4 // missed heartbeats or deregistered
)

// Enum value maps for WorkerState.
var (
	WorkerState_name = map[int32]string{
		0: "STARTING",
		1: "READY",
		2: "BUSY",
		3: "DRAINING",
		4: "DEAD",
	}
	WorkerState_value = map[string]int32{
		"STARTING": 0,
		"READY":    1,
		"BUSY":     2,
		"DRAINING": 3,
		"DEAD":     4,
	}
)

func (x WorkerState) Enum() *WorkerState {
	p := new(WorkerState)
	*p = x
	return p
}

func (x WorkerState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkerState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_registry_proto_enumTypes[0].Descriptor()
}

func (WorkerState) Type() protoreflect.EnumType {
	return &file_proto_registry_proto_enumTypes[0]
}

func (x WorkerState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkerState.Descriptor instead.
func (WorkerState) EnumDescriptor() ([]byte, []int) {
	return file_proto_registry_proto_rawDescGZIP(), []int{0}
}

// WorkerInfo is sent on registration.
// It tells the control plane everything it needs to route and cost-aware dispatch.
type WorkerInfo struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	WorkerId     string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`             // stable unique ID (e.g. pod name)
	Address      string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`                               // host:port the worker listens on for inference requests
	GpuType      string                 `protobuf:"bytes,3,opt,name=gpu_type,json=gpuType,proto3" json:"gpu_type,omitempty"`                // e.g. "Apple M2", "NVIDIA L4", "NVIDIA A100"
	VramBytes    uint64                 `protobuf:"varint,4,opt,name=vram_bytes,json=vramBytes,proto3" json:"vram_bytes,omitempty"`         // total VRAM in bytes (0 for CPU-only workers)
	ModelsLoaded []string               `protobuf:"bytes,5,rep,name=models_loaded,json=modelsLoaded,proto3" json:"models_loaded,omitempty"` // model IDs loaded, e.g. "llama3.2:3b"
	// Provider-agnostic metadata — control plane uses these for routing decisions,
	// never for provisioning logic (that lives in WorkerProvisioner).
	Backend       string  `protobuf:"bytes,6,opt,name=backend,proto3" json:"backend,omitempty"`                                // "ollama" | "vllm" | "llama.cpp" | "jetstream"
	Provider      string  `protobuf:"bytes,7,opt,name=provider,proto3" json:"provider,omitempty"`                              // "local" | "gcp" | "aws" | "azure" | "on_prem"
	Hardware      string  `protobuf:"bytes,8,opt,name=hardware,proto3" json:"hardware,omitempty"`                              // "apple_m2" | "nvidia_l4" | "nvidia_a100" | "amd_mi300" | "cpu"
	CostPerHour   float64 `protobuf:"fixed64,9,opt,name=cost_per_hour,json=costPerHour,proto3" json:"cost_per_hour,omitempty"` // 0.0 for local workers; actual $/hr for cloud workers
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerInfo) Reset() {
	*x = WorkerInfo{}
	mi := &file_proto_registry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerInfo) ProtoMessage() {}

func (x *WorkerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_registry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerInfo.ProtoReflect.Descriptor instead.
func (*WorkerInfo) Descriptor() ([]byte, []int) {
	return file_proto_registry_proto_rawDescGZIP(), []int{0}
}

func (x *WorkerInfo) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *WorkerInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *WorkerInfo) GetGpuType() string {
	if x != nil {
		return x.GpuType
	}
	return ""
}

func (x *WorkerInfo) GetVramBytes() uint64 {
	if x != nil {
		return x.VramBytes
	}
	return 0
}

func (x *WorkerInfo) GetModelsLoaded() []string {
	if x != nil {
		return x.ModelsLoaded
	}
	return nil
}

func (x *WorkerInfo) GetBackend() string {
	if x != nil {
		return x.Backend
	}
	return ""
}

func (x *WorkerInfo) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *WorkerInfo) GetHardware() string {
	if x != nil {
		return x.Hardware
	}
	return ""
}

func (x *WorkerInfo) GetCostPerHour() float64 {
	if x != nil {
		return x.CostPerHour
	}
	return 0
}

type RegisterResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Ok                    bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message               string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	HeartbeatIntervalSecs uint32                 `protobuf:"varint,3,opt,name=heartbeat_interval_secs,json=heartbeatIntervalSecs,proto3" json:"heartbeat_interval_secs,omitempty"` // control plane tells worker how often to heartbeat
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_proto_registry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_registry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_registry_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterResponse) GetHeartbeatIntervalSecs() uint32 {
	if x != nil {
		return x.HeartbeatIntervalSecs
	}
	return 0
}

// HeartbeatRequest is sent every heartbeat_interval_secs by the worker.
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	State         WorkerState            `protobuf:"varint,2,opt,name=state,proto3,enum=registry.WorkerState" json:"state,omitempty"` // worker self-reports its current state
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_registry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_registry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_registry_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *HeartbeatRequest) GetState() WorkerState {
	if x != nil {
		return x.State
	}
	return WorkerState_STARTING
}

type HeartbeatResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Ok    bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	// If drain = true, the control plane wants this worker to begin draining.
	// Worker stops accepting new requests, finishes in-flight, then deregisters.
	Drain         bool `protobuf:"varint,2,opt,name=drain,proto3" json:"drain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_proto_registry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_registry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_registry_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HeartbeatResponse) GetDrain() bool {
	if x != nil {
		return x.Drain
	}
	return false
}

// LoadReport is sent alongside or after each heartbeat with current metrics.
type LoadReport struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WorkerId       string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	QueueDepth     uint32                 `protobuf:"varint,2,opt,name=queue_depth,json=queueDepth,proto3" json:"queue_depth,omitempty"`                // number of requests currently queued or in-flight
	RequestsPerSec float64                `protobuf:"fixed64,3,opt,name=requests_per_sec,json=requestsPerSec,proto3" json:"requests_per_sec,omitempty"` // smoothed request rate over last 10 seconds
	AvgLatencyMs   float64                `protobuf:"fixed64,4,opt,name=avg_latency_ms,json=avgLatencyMs,proto3" json:"avg_latency_ms,omitempty"`       // smoothed avg latency over last 10 seconds
	VramUsedBytes  uint64                 `protobuf:"varint,5,opt,name=vram_used_bytes,json=vramUsedBytes,proto3" json:"vram_used_bytes,omitempty"`     // current VRAM usage
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LoadReport) Reset() {
	*x = LoadReport{}
	mi := &file_proto_registry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadReport) ProtoMessage() {}

func (x *LoadReport) ProtoReflect() protoreflect.Message {
	mi := &file_proto_registry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadReport.ProtoReflect.Descriptor instead.
func (*LoadReport) Descriptor() ([]byte, []int) {
	return file_proto_registry_proto_rawDescGZIP(), []int{4}
}

func (x *LoadReport) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *LoadReport) GetQueueDepth() uint32 {
	if x != nil {
		return x.QueueDepth
	}
	return 0
}

func (x *LoadReport) GetRequestsPerSec() float64 {
	if x != nil {
		return x.RequestsPerSec
	}
	return 0
}

func (x *LoadReport) GetAvgLatencyMs() float64 {
	if x != nil {
		return x.AvgLatencyMs
	}
	return 0
}

func (x *LoadReport) GetVramUsedBytes() uint64 {
	if x != nil {
		return x.VramUsedBytes
	}
	return 0
}

type DeregisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterRequest) Reset() {
	*x = DeregisterRequest{}
	mi := &file_proto_registry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterRequest) ProtoMessage() {}

func (x *DeregisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_registry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterRequest.ProtoReflect.Descriptor instead.
func (*DeregisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_registry_proto_rawDescGZIP(), []int{5}
}

func (x *DeregisterRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_registry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_registry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_registry_proto_rawDescGZIP(), []int{6}
}

var File_proto_registry_proto protoreflect.FileDescriptor

const file_proto_registry_proto_rawDesc = "" +
	"\n" +
	"\x14proto/registry.proto\x12\bregistry\"\x98\x02\n" +
	"\n" +
	"WorkerInfo\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x19\n" +
	"\bgpu_type\x18\x03 \x01(\tR\agpuType\x12\x1d\n" +
	"\n" +
	"vram_bytes\x18\x04 \x01(\x04R\tvramBytes\x12#\n" +
	"\rmodels_loaded\x18\x05 \x03(\tR\fmodelsLoaded\x12\x18\n" +
	"\abackend\x18\x06 \x01(\tR\abackend\x12\x1a\n" +
	"\bprovider\x18\a \x01(\tR\bprovider\x12\x1a\n" +
	"\bhardware\x18\b \x01(\tR\bhardware\x12\"\n" +
	"\rcost_per_hour\x18\t \x01(\x01R\vcostPerHour\"t\n" +
	"\x10RegisterResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x126\n" +
	"\x17heartbeat_interval_secs\x18\x03 \x01(\rR\x15heartbeatIntervalSecs\"\\\n" +
	"\x10HeartbeatRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12+\n" +
	"\x05state\x18\x02 \x01(\x0e2\x15.registry.WorkerStateR\x05state\"9\n" +
	"\x11HeartbeatResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05drain\x18\x02 \x01(\bR\x05drain\"\xc2\x01\n" +
	"\n" +
	"LoadReport\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x1f\n" +
	"\vqueue_depth\x18\x02 \x01(\rR\n" +
	"queueDepth\x12(\n" +
	"\x10requests_per_sec\x18\x03 \x01(\x01R\x0erequestsPerSec\x12$\n" +
	"\x0eavg_latency_ms\x18\x04 \x01(\x01R\favgLatencyMs\x12&\n" +
	"\x0fvram_used_bytes\x18\x05 \x01(\x04R\rvramUsedBytes\"0\n" +
	"\x11DeregisterRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\"\a\n" +
	"\x05Empty*H\n" +
	"\vWorkerState\x12\f\n" +
	"\bSTARTING\x10\x00\x12\t\n" +
	"\x05READY\x10\x01\x12\b\n" +
	"\x04BUSY\x10\x02\x12\f\n" +
	"\bDRAINING\x10\x03\x12\b\n" +
	"\x04DEAD\x10\x042\x85\x02\n" +
	"\x0eWorkerRegistry\x12<\n" +
	"\bRegister\x12\x14.registry.WorkerInfo\x1a\x1a.registry.RegisterResponse\x12D\n" +
	"\tHeartbeat\x12\x1a.registry.HeartbeatRequest\x1a\x1b.registry.HeartbeatResponse\x12:\n" +
	"\n" +
	"Deregister\x12\x1b.registry.DeregisterRequest\x1a\x0f.registry.Empty\x123\n" +
	"\n" +
	"ReportLoad\x12\x14.registry.LoadReport\x1a\x0f.registry.EmptyB/Z-github.com/atharva/llm-serving-platform/protob\x06proto3"

var (
	file_proto_registry_proto_rawDescOnce sync.Once
	file_proto_registry_proto_rawDescData []byte
)

func file_proto_registry_proto_rawDescGZIP() []byte {
	file_proto_registry_proto_rawDescOnce.Do(func() {
		file_proto_registry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_registry_proto_rawDesc), len(file_proto_registry_proto_rawDesc)))
	})
	return file_proto_registry_proto_rawDescData
}

var file_proto_registry_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_registry_proto_goTypes = []any{
	(WorkerState)(0),          // 0: registry.WorkerState
	(*WorkerInfo)(nil),        // 1: registry.WorkerInfo
	(*RegisterResponse)(nil),  // 2: registry.RegisterResponse
	(*HeartbeatRequest)(nil),  // 3: registry.HeartbeatRequest
	(*HeartbeatResponse)(nil), // 4: registry.HeartbeatResponse
	(*LoadReport)(nil),        // 5: registry.LoadReport
	(*DeregisterRequest)(nil), // 6: registry.DeregisterRequest
	(*Empty)(nil),             // 7: registry.Empty
}
var file_proto_registry_proto_depIdxs = []int32{
	0, // 0: registry.HeartbeatRequest.state:type_name -> registry.WorkerState
	1, // 1: registry.WorkerRegistry.Register:input_type -> registry.WorkerInfo
	3, // 2: registry.WorkerRegistry.Heartbeat:input_type -> registry.HeartbeatRequest
	6, // 3: registry.WorkerRegistry.Deregister:input_type -> registry.DeregisterRequest
	5, // 4: registry.WorkerRegistry.ReportLoad:input_type -> registry.LoadReport
	2, // 5: registry.WorkerRegistry.Register:output_type -> registry.RegisterResponse
	4, // 6: registry.WorkerRegistry.Heartbeat:output_type -> registry.HeartbeatResponse
	7, // 7: registry.WorkerRegistry.Deregister:output_type -> registry.Empty
	7, // 8: registry.WorkerRegistry.ReportLoad:output_type -> registry.Empty
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_registry_proto_init() }
func file_proto_registry_proto_init() {
	if File_proto_registry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_registry_proto_rawDesc), len(file_proto_registry_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_registry_proto_goTypes,
		DependencyIndexes: file_proto_registry_proto_depIdxs,
		EnumInfos:         file_proto_registry_proto_enumTypes,
		MessageInfos:      file_proto_registry_proto_msgTypes,
	}.Build()
	File_proto_registry_proto = out.File
	file_proto_registry_proto_goTypes = nil
	file_proto_registry_proto_depIdxs = nil
}
