// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.1
// source: proto/registry.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkerRegistry_Register_FullMethodName   = "/registry.WorkerRegistry/Register"
	WorkerRegistry_Heartbeat_FullMethodName  = "/registry.WorkerRegistry/Heartbeat"
	WorkerRegistry_Deregister_FullMethodName = "/registry.WorkerRegistry/Deregister"
	WorkerRegistry_ReportLoad_FullMethodName = "/registry.WorkerRegistry/ReportLoad"
)

// WorkerRegistryClient is the client API for WorkerRegistry service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WorkerRegistry is the gRPC service the control plane exposes.
// Workers call these RPCs to join the fleet, stay alive, and report load.
type WorkerRegistryClient interface {
	Register(ctx context.Context, in *WorkerInfo, opts ...grpc.CallOption) (*RegisterResponse, error)
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	Deregister(ctx context.Context, in *DeregisterRequest, opts ...grpc.CallOption) (*Empty, error)
	ReportLoad(ctx context.Context, in *LoadReport, opts ...grpc.CallOption) (*Empty, error)
}

type workerRegistryClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkerRegistryClient(cc grpc.ClientConnInterface) WorkerRegistryClient {
	return &workerRegistryClient{cc}
}

func (c *workerRegistryClient) Register(ctx context.Context, in *WorkerInfo, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, WorkerRegistry_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerRegistryClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, WorkerRegistry_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerRegistryClient) Deregister(ctx context.Context, in *DeregisterRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, WorkerRegistry_Deregister_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerRegistryClient) ReportLoad(ctx context.Context, in *LoadReport, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, WorkerRegistry_ReportLoad_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkerRegistryServer is the server API for WorkerRegistry service.
// All implementations must embed UnimplementedWorkerRegistryServer
// for forward compatibility.
//
// WorkerRegistry is the gRPC service the control plane exposes.
// Workers call these RPCs to join the fleet, stay alive, and report load.
type WorkerRegistryServer interface {
	Register(context.Context, *WorkerInfo) (*RegisterResponse, error)
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	Deregister(context.Context, *DeregisterRequest) (*Empty, error)
	ReportLoad(context.Context, *LoadReport) (*Empty, error)
	mustEmbedUnimplementedWorkerRegistryServer()
}

// UnimplementedWorkerRegistryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkerRegistryServer struct{}

func (UnimplementedWorkerRegistryServer) Register(context.Context, *WorkerInfo) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedWorkerRegistryServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedWorkerRegistryServer) Deregister(context.Context, *DeregisterRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Deregister not implemented")
}
func (UnimplementedWorkerRegistryServer) ReportLoad(context.Context, *LoadReport) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportLoad not implemented")
}
func (UnimplementedWorkerRegistryServer) mustEmbedUnimplementedWorkerRegistryServer() {}
func (UnimplementedWorkerRegistryServer) testEmbeddedByValue()                        {}

// UnsafeWorkerRegistryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkerRegistryServer will
// result in compilation errors.
type UnsafeWorkerRegistryServer interface {
	mustEmbedUnimplementedWorkerRegistryServer()
}

func RegisterWorkerRegistryServer(s grpc.ServiceRegistrar, srv WorkerRegistryServer) {
	// If the following call panics, it indicates UnimplementedWorkerRegistryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkerRegistry_ServiceDesc, srv)
}

func _WorkerRegistry_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkerInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerRegistryServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerRegistry_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerRegistryServer).Register(ctx, req.(*WorkerInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerRegistry_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerRegistryServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerRegistry_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerRegistryServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerRegistry_Deregister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeregisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerRegistryServer).Deregister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerRegistry_Deregister_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerRegistryServer).Deregister(ctx, req.(*DeregisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerRegistry_ReportLoad_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerRegistryServer).ReportLoad(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerRegistry_ReportLoad_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerRegistryServer).ReportLoad(ctx, req.(*LoadReport))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkerRegistry_ServiceDesc is the grpc.ServiceDesc for WorkerRegistry service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkerRegistry_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "registry.WorkerRegistry",
	HandlerType: (*WorkerRegistryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _WorkerRegistry_Register_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _WorkerRegistry_Heartbeat_Handler,
		},
		{
			MethodName: "Deregister",
			Handler:    _WorkerRegistry_Deregister_Handler,
		},
		{
			MethodName: "ReportLoad",
			Handler:    _WorkerRegistry_ReportLoad_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/registry.proto",
}
